platform: x64 

init:
- git --version
  
install:
# http://help.appveyor.com/discussions/problems/6312-curl-command-not-found
- set PATH=%PATH%;C:\Program Files\Git\mingw64\bin

# Update GIT submodules
- git submodule update --init --recursive

# Download latest stable Stack tool
- curl -sS -ostack.zip -L --insecure https://get.haskellstack.org/stable/windows-x86_64.zip
- 7z x stack.zip stack.exe
- stack --version

# Install Microsoft Z3 from NuGet
- curl -fsSL https://github.com/Z3Prover/z3/releases/download/Nightly/z3-4.8.7-x64-win.zip -o z3-4.8.7-x64-win.zip
- 7z e z3-4.8.7-x64-win.zip -oc:\projects\liquidhaskell\z3_downloaded -r -y

- refreshenv

- set PATH=C:\projects\liquidhaskell\z3_downloaded;%PATH%
- z3 --version

build_script:
# Build LiquidHaskell
- echo "" | stack --no-terminal build --copy-bins --local-bin-path .

# Copy runtime DLLs
- call appveyor-copy.bat

# Test if they are working
- fixpoint --version
- liquid --version

test_script:
- echo "" | stack --no-terminal test liquidhaskell --fast --test-arguments "-p Micro"
