build: off

environment:
    LIQUIDHASKELL_TEST_ENVIRONMENT: win
    LIQUIDHASKELL_HEAVYTEST_PERCENTAGE: 0
    TASTY_HIDE_SUCCESSES: True

before_build:
- curl -fsSL https://github.com/Z3Prover/z3/releases/download/Nightly/z3-4.8.7-x64-win.zip -o z3-4.8.7-x64-win.zip
- 7z e z3-4.8.7-x64-win.zip -oc:\projects\liquidhaskell\z3_downloaded -r -y
- choco install -y cabal
- choco install -y ghc --version 8.6.5
- refreshenv
- set PATH=C:\projects\liquidhaskell\z3_downloaded;%PATH%
- ghc --version
- z3 --version

skip_tags: true

build_script:
# Build LiquidHaskell
- echo "" | stack --no-terminal build --copy-bins --local-bin-path .

# Copy runtime DLLs
- call appveyor-copy.bat

# Test if they are working
- fixpoint --version
- liquid --version

# ZIP execturable 
- 7z a liquidhaskell.zip liquid.exe fixpoint.exe .\include\CoreToLogic.lg LICENSE LICENSE_Z3 libstdc++-6.dll libgcc_s_seh-1.dll libwinpthread-1.dll %APPVEYOR_BUILD_FOLDER%\z3x64win.4.8.7\tools\*.exe %APPVEYOR_BUILD_FOLDER%\z3x64win.4.8.7\lib\*.dll %APPVEYOR_BUILD_FOLDER%\z3x64win.4.8.7\*.dll

test_script:
- echo "" | stack --no-terminal test liquidhaskell --fast --test-arguments "-p Micro"

artifacts:
- path: liquidhaskell.zip
  name: LiquidHaskell
