platform: x64

init:
- git --version
  
install:
# http://help.appveyor.com/discussions/problems/6312-curl-command-not-found
- set PATH=%PATH%;C:\Program Files\Git\mingw64\bin

# Update GIT submodules
- git submodule update --init --recursive

# Download latest stable Stack tool
- curl -sS -ostack.zip -L --insecure https://get.haskellstack.org/stable/windows-x86_64.zip
- 7z x stack.zip stack.exe
- stack --version

# Install Microsoft Z3 from NuGet
- nuget install z3x64win -Version 4.5.0.1	

- set PATH=%PATH%;%cd%;%cd%\z3x64win.4.5.0.1\tools
- z3 --version

build_script:
# Copy runtime DLLs
- cmd: echo "" | stack exec -- where libstdc++-6.dll > lib.txt
- cmd: echo "" | stack exec -- where libgcc_s_seh-1.dll >> lib.txt
- cmd: echo "" | stack exec -- where libwinpthread-1.dll >> lib.txt
- cmd: for /F %i IN (lib.txt) do copy /Y "%i" .\
- cmd: del /q lib.txt

# Test build liquid-fixpoint
- cd liquid-fixpoint
- echo "" | stack --no-terminal build --copy-bins --local-bin-path ..
- cd ..
- fixpoint --version

# Build LiquidHaskell
- echo "" | stack --no-terminal build --copy-bins --local-bin-path .
- liquid --version

# ZIP execturable
- 7z a liquidhaskell.zip liquid.exe fixpoint.exe LICENSE LICENSE_Z3 libstdc++-6.dll libgcc_s_seh-1.dll libwinpthread-1.dll %APPVEYOR_BUILD_FOLDER%\z3x64win.4.5.0.1\tools\*.exe %APPVEYOR_BUILD_FOLDER%\z3x64win.4.5.0.1\lib\*.dll %APPVEYOR_BUILD_FOLDER%\z3x64win.4.5.0.1\*.dll

test_script:
# The ugly echo "" hack is to avoid complaints about 0 being an invalid file
# descriptor
#- echo "" | stack --no-terminal test --jobs 1 --verbose

artifacts:
- path: liquidhaskell.zip
  name: LiquidHaskell