# Disabled cache in hope of improving reliability of AppVeyor builds
#cache:
#- "c:\\sr" # stack root, short paths == fewer problems

clone_folder: "c:\\lh"
environment:
  global:
    STACK_ROOT: "c:\\sr"
    TMP: "c:\\tmp"

init:
- git --version
- for /f %%i in ("stack exec -- 'which liquid.exe | sed \"s|^/c/|c:\\|;s|/|\\|g\"'") do set LH_EXECUTABLE=%%i
- for /f %%i in ("stack exec -- 'which fixpoint.exe | sed \"s|^/c/|c:\\|;s|/|\\|g\"'") do set FP_EXECUTABLE=%%i
- echo %LH_EXECUTABLE% %FP_EXECUTABLE%
  
install:
# http://help.appveyor.com/discussions/problems/6312-curl-command-not-found
- set PATH=C:\Program Files\Git\mingw64\bin;%PATH%

# Download latest stable Stack tool
- curl -sS -ostack.zip -L --insecure https://get.haskellstack.org/stable/windows-i386.zip
- 7z x stack.zip stack.exe
- stack --version

# Install Microsoft Z3 from NuGet
- nuget install z3x64win -Version 4.5.0.1	

- set PATH=z3x64win.4.5.0.1\tools;%PATH%
- z3 --version

# Update GIT submodule
- git submodule update --init --recursive

build_script:
- stack setup > nul
- echo "" | stack --no-terminal build --jobs 1
- dir /s .stack-work\\

# ZIP execturable
- 7z a liquidhaskell.zip LICENSE %APPVEYOR_BUILD_FOLDER%\z3x64win.4.5.0.1\tools\*.exe %APPVEYOR_BUILD_FOLDER%\z3x64win.4.5.0.1\lib\*.dll %APPVEYOR_BUILD_FOLDER%\z3x64win.4.5.0.1\*.dll %LH_EXECUTABLE% %FP_EXECUTABLE%

test_script:
# The ugly echo "" hack is to avoid complaints about 0 being an invalid file
# descriptor
#- echo "" | stack --no-terminal test --jobs 1 --verbose

artifacts:
- path: "C:\\lh\\.stack-work\\logs\\"
  name: Logs
- path: liquidhaskell.zip
  name: LiquidHaskell