
resolver: nightly-2018-06-27

packages:
- liquid-fixpoint/
- '.'

extra-deps:
- csv-table-0.1.0.1
- dotgen-0.4.2
- fgl-visualize-0.1.0.1
- intern-0.9.2
- located-base-0.1.1.1
- tasty-rerun-1.1.12
- git: https://github.com/deepfire/text-format.git
  commit: a1cda87c222d422816f956c7272e752ea12dbe19

flags:
  liquidhaskell:
    devel: true

extra-package-dbs: []
