flags:
  liquid-platform:
    devel: true
extra-package-dbs: []
ghc-options:
  hscolour: -w
allow-newer: true # 8.10.1
packages:
- liquid-fixpoint
- liquid-ghc-prim
- liquid-base
- liquid-bytestring
- liquid-prelude
- liquid-vector
- liquid-containers
- liquid-parallel
- liquid-platform
- .
extra-deps:
- hashable-1.3.0.0
- rest-rewrite-0.1.1

resolver: lts-18.14
compiler: ghc-8.10.7

nix:
  shell-file: shell-stack.nix
  path: ["nixpkgs=./nixpkgs.nix"]
