flags:
  liquidhaskell:
    devel: true
extra-package-dbs: []
ghc-options:
  hscolour: -w
allow-newer: true # 8.10.1
packages:
- liquid-prelude
- liquid-fixpoint
- .
extra-deps:
- tasty-rerun-1.1.14
- fgl-visualize-0.1.0.1
- located-base-0.1.1.1
- hashable-1.3.0.0
- text-format-0.3.2
- optics-0.2
# Required for the 8.10.1 build
- Diff-0.3.4
- aeson-1.4.7.1
- git: https://github.com/well-typed/optics.git
  commit: 0a4940cc927df3f50151692282f8b148bf326886
  subdirs:
    - optics-core
    - optics-th
resolver: lts-15.4
compiler: ghc-8.10.1
