flags:
  liquidhaskell:
    devel: true
  liquid-platform:
    devel: true
  tests:
    stack: true
extra-package-dbs: []
ghc-options:
  hscolour: -w
  liquidhaskell-boot: -j
  liquidhaskell: -j
packages:
- liquid-fixpoint
- liquid-prelude
- liquid-vector
- liquid-parallel
- liquid-platform
- liquidhaskell-boot
- tests
- tests/benchmarks/popl18/lib
- benchmark-timings
- .
extra-deps:
- smtlib-backends-0.3@rev:1
- smtlib-backends-process-0.3@rev:1
- git: https://github.com/qnikst/ghc-timings-report
  commit: 45ef3498e35897712bde8e002ce18df6d55f8b15

resolver: nightly-2023-11-27

nix:
  packages: [cacert, git, hostname, z3]
  path: [nixpkgs=./nixpkgs.nix]
