---
version: 2.0

jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-12.2
    steps:
      - add_ssh_keys
      - run: apt-get install z3
      - checkout
      - run: git submodule init
      #- run: find .git
      #- run: sed -i '/fixpoint.git/a fetch = +refs/pull/*/head:refs/remotes/origin/pr/*' .git/modules/liquid-fixpoint/config
      - run: git submodule update
      - restore_cache:
          keys:
            - stack-{{ checksum "stack.yaml" }}
      - run:
          name: Dependencies
          command: |
            stack setup
            # rm -fr $(stack path --dist-dir) $(stack path --local-install-root)
            stack build liquidhaskell --only-dependencies --test --no-run-tests
      - save_cache:
          key: stack-{{ checksum "stack.yaml" }}
          paths:
            - ~/.stack
            - ./.stack-work
      - run:
          name: Test
          command: |
            stack clean
            mkdir -p /tmp/junit
            stack test liquidhaskell:test --flag liquidhaskell:include --flag liquidhaskell:devel --test-arguments="-t 1200s --xml=/tmp/junit/main-test-results.xml": #--liquid-opts='--cores=1'":
            stack test liquidhaskell:liquidhaskell-parser --test-arguments="-j2 --xml=/tmp/junit/parser-test-results.xml":
            stack sdist
            stack haddock liquidhaskell --flag liquidhaskell:-devel --no-haddock-deps --haddock-arguments="--no-print-missing-docs --odir=$CIRCLE_ARTIFACTS"
      - store_test_results:
          path: /tmp/junit
      # if you want to store logs
      # - store_artifacts:
      #    path: tests/logs/cur
      - run:
          name: Dist
          command: stack sdist
