site_name: LiquidHaskell 

nav:
    - Online: "https://liquid-demo.programming.systems/index.html"
    - Blog: "https://ucsd-progsys.github.io/liquidhaskell-blog/"
    - Plugin: plugin.md 
    - Legacy: legacy.md
    - Options: options.md
    - Specifications: specifications.md
    - Community: contributing.md    
    - Development: develop.md         

theme: litera
