site_name: LiquidHaskell

nav:
    - Install:
      - 'External Dependencies': install.md
      - 'Plugin': plugin.md
      - 'Legacy Executable': legacy.md
    - Play: "https://liquid-demo.programming.systems/index.html"
    - Learn:
      - Blog: "https://ucsd-progsys.github.io/liquidhaskell-blog/"
      - Options: options.md
      - Specifications: specifications.md
    - "Get Involved": contributing.md

theme: litera

markdown_extensions:
    - toc:
        permalink: true
