
# Deploy the docs when they are pushed to 'develop'

# Based off
# https://squidfunk.github.io/mkdocs-material/publishing-your-site/?h=deploy#with-github-actions

name: Deploy LiquidHaskell Docs
on:
  push:
    branches:
      - develop
jobs:
  deploy-docs-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install \
              mkdocs-material \
              mkdocs-awesome-pages-plugin \
              git+https://github.com/jldiaz/mkdocs-plugin-tags.git
      - run: mkdocs gh-deploy --force
  
